# Generated by Django 3.2.13 on 2022-06-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_image_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processed_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
